username: testuser
password: null
servers: localhost:9093
mytopics:
  test_stream:
    classification: kilonova
    probability: 0.75
group_id: test_group
testing: true
skyportal_url: http://localhost:5000
skyportal_token: 6976b3cb-d79a-44b9-83a1-b15aa2549052