username: testuser
password: null
servers: localhost:9093
mytopics:
  ["test_stream"]
group_id: test_group
testing: true
skyportal_url: http://localhost:5000
skyportal_token: 1a7141f1-3e6e-483e-badd-efe5fa0e8597
